# Generated by Django 6.0.6 on 2026-06-28 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmenityItems',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('item_type', models.CharField(choices=[('DRINK', 'Kinywaji'), ('SNACK', 'Chakula Chepesi')], max_length=5)),
                ('dietary_type', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.IntegerField(choices=[(1, 'Wazi/Active'), (0, 'Zimwa/Inactive')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Huduma za Ndani (Amenity Items)',
                'db_table': 'amenity_items',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('seat_number', models.IntegerField()),
                ('final_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ticket_hash', models.CharField(max_length=64, unique=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('booking_status', models.CharField(choices=[('CONFIRMED', 'Imethibitishwa (Confirmed)'), ('PENDING', 'Inasubiri Malipo (Pending)'), ('CANCELLED', 'Imeghairishwa (Cancelled)')], default='PENDING', max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tiketi Zilizokatiwa (Bookings)',
                'db_table': 'bookings',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100, unique=True)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('contact_email', models.CharField(max_length=100)),
                ('is_verified', models.IntegerField(choices=[(1, 'Ndiyo'), (0, 'Hapana')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Makampuni ya Mabasi (Companies)',
                'db_table': 'companies',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('route_id', models.AutoField(primary_key=True, serialize=False)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estimated_duration_hours', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'verbose_name_plural': 'Ruti za Safari (Routes)',
                'db_table': 'routes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Msimamizi Mkuu (Admin)'), ('OPERATOR', 'Wakala wa Basi (Operator)'), ('CUSTOMER', 'Abiria (Customer)')], default='CUSTOMER', max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Watumiaji (Users)',
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Buses',
            fields=[
                ('bus_id', models.AutoField(primary_key=True, serialize=False)),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('total_capacity', models.IntegerField()),
                ('bus_type', models.CharField(choices=[('LUXURY', 'Premium Luxury'), ('SEMI_LUXURY', 'Semi Luxury'), ('ORDINARY', 'Ordinary Class')], default='ORDINARY', max_length=11)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tickets.companies')),
            ],
            options={
                'verbose_name_plural': 'Mabasi (Buses)',
                'db_table': 'buses',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('payment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('M-PESA', 'Vodacom M-Pesa'), ('TIGO PESA', 'Tigo Pesa'), ('AIRTEL MONEY', 'Airtel Money'), ('CRDB BANK', 'CRDB Bank Card')], max_length=15)),
                ('transaction_reference', models.CharField(max_length=100, unique=True)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('raw_api_payload', models.JSONField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('COMPLETED', 'Imekamilika (Completed)'), ('FAILED', 'Imefeli (Failed)'), ('PENDING', 'Inasubiri (Pending)')], default='PENDING', max_length=9)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='tickets.bookings')),
            ],
            options={
                'verbose_name_plural': 'Malipo (Payments)',
                'db_table': 'payments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tickets.buses')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tickets.routes')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tickets.users')),
            ],
            options={
                'verbose_name_plural': 'Ratiba za Safari (Schedules)',
                'db_table': 'schedules',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='bookings',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tickets.schedules'),
        ),
        migrations.CreateModel(
            name='SeatLocks',
            fields=[
                ('lock_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('seat_number', models.IntegerField()),
                ('locked_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('lock_status', models.CharField(choices=[('ACTIVE', 'Active Lock'), ('EXPIRED', 'Expired Lock'), ('RELEASED', 'Released')], default='ACTIVE', max_length=20)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tickets.schedules')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tickets.users')),
            ],
            options={
                'verbose_name_plural': 'Viti Vilivyofungwa (Seat Locks)',
                'db_table': 'seat_locks',
                'managed': True,
                'unique_together': {('schedule', 'seat_number', 'lock_status')},
            },
        ),
        migrations.AddField(
            model_name='bookings',
            name='lock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tickets.seatlocks'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='refunded_by',
            field=models.ForeignKey(blank=True, db_column='refunded_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bookings_refunded_by_set', to='tickets.users'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tickets.users'),
        ),
        migrations.AlterUniqueTogether(
            name='bookings',
            unique_together={('schedule', 'seat_number', 'booking_status')},
        ),
    ]
